services:
  - type: web
    name: kemp-contabilita-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ANTHROPIC_KEY
        sync: false
      - key: SPREADSHEET_ID
        sync: false
      - key: GOOGLE_CREDS
        sync: false
